#!/usr/bin/env bun
/**
 * gen-animations-gallery.ts — generate the local animation gallery data.
 *
 * The checked-in gallery lives under `gallery/`. It is deliberately local to
 * this package so a standalone checkout can regenerate and review it without
 * the framework's Storybook app. The script invokes the Rust engine directly,
 * just like `gen-cn-conflict-map.ts` and `gen-style-packs.ts`.
 *
 *   --dump-animation-classes     → JSON array of every `animations::ANIMATIONS`
 *                                   class name (the gallery's render list)
 *   --dump-animation-gallery-css → the compiled CSS for all of them, plus the
 *                                   reduced-motion guard from scoped output.
 *
 * Both are derived from `animations::ANIMATIONS` at generation time, so the
 * gallery can never drift from the real catalog — no hand-maintained class
 * list, the same discipline Slice 10's `inventory_is_complete` gate uses.
 *
 * Run: `bun run gen:animations-gallery`.
 *   bun scripts/gen-animations-gallery.ts --check  # CI: fail if stale
 *
 * FIXTURE-SCAN MODE (the same shape as the conflict-map generator's target
 * override).
 * `ANIMATIONS_GALLERY_CSS_TARGET` / `ANIMATIONS_GALLERY_CLASSES_TARGET` repoint
 * the `--check` comparison at different committed files instead of the real
 * generated targets. `ANIMATIONS_GALLERY_CLASSES_JSON` /
 * `ANIMATIONS_GALLERY_CSS_DUMP`, separately, repoint the input at committed
 * fixture files holding the same output shapes, which keeps gate tests
 * hermetic when a Rust toolchain is unavailable.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = resolve(__dirname, '..')
const repoRoot = pkgRoot

function resolveBinary(): string {
  const ext = process.platform === 'win32' ? '.exe' : ''
  const candidates = [
    resolve(repoRoot, 'target/release', `aihu-css-compile${ext}`),
    resolve(repoRoot, 'target/debug', `aihu-css-compile${ext}`),
  ]
  for (const c of candidates) {
    if (existsSync(c)) return c
  }
  throw new Error(
    `aihu-css-compile binary not found. Run \`cargo build --release\` first. Checked: ${candidates.join(', ')}`,
  )
}

/**
 * Bounded spawn. An unbounded `execFileSync` against this binary is the same
 * hang that stalled a docs build for 10 minutes at 0% CPU (see the
 * spawn-bounds note in `src/index.ts`): with no timer armed
 * spawnSync's uv loop blocks in kevent with no deadline, forever. These dumps
 * complete in milliseconds, so 60 s is a generous ceiling that still turns a
 * wedged generator into a fast, named failure. `maxBuffer` is explicit because
 * the gallery CSS dump is the one output here that could plausibly outgrow
 * node's inherited 1 MiB default.
 */
const DUMP_SPAWN_OPTS = {
  encoding: 'utf-8',
  timeout: 60_000,
  maxBuffer: 64 * 1024 * 1024,
  killSignal: 'SIGKILL',
} as const

const classesJson = process.env.ANIMATIONS_GALLERY_CLASSES_JSON
  ? readFileSync(resolve(repoRoot, process.env.ANIMATIONS_GALLERY_CLASSES_JSON), 'utf8')
  : execFileSync(resolveBinary(), ['--dump-animation-classes'], DUMP_SPAWN_OPTS)
const classes = JSON.parse(classesJson) as string[]
const css = process.env.ANIMATIONS_GALLERY_CSS_DUMP
  ? readFileSync(resolve(repoRoot, process.env.ANIMATIONS_GALLERY_CSS_DUMP), 'utf8')
  : execFileSync(resolveBinary(), ['--dump-animation-gallery-css'], DUMP_SPAWN_OPTS)

const storiesDir = resolve(repoRoot, 'gallery')
const cssTarget = process.env.ANIMATIONS_GALLERY_CSS_TARGET
  ? resolve(repoRoot, process.env.ANIMATIONS_GALLERY_CSS_TARGET)
  : resolve(storiesDir, 'animations-gallery.generated.css')
const classesTarget = process.env.ANIMATIONS_GALLERY_CLASSES_TARGET
  ? resolve(repoRoot, process.env.ANIMATIONS_GALLERY_CLASSES_TARGET)
  : resolve(storiesDir, 'animations-gallery.generated.ts')

const classesOut = `// AUTO-GENERATED by scripts/gen-animations-gallery.ts — DO NOT EDIT.
// Source of truth: aihu-css-core \`animations::ANIMATIONS\`. Regenerate with
// \`bun run gen:animations-gallery\`. Hand-edits
// will be lost.

/** Every ported tailwind-animations class name, in the catalog's own sorted
 * order — the demo gallery's render list. */
export const ANIMATION_GALLERY_CLASSES: readonly string[] = ${JSON.stringify(classes, null, 2)}
`

const check = process.argv.includes('--check')

if (check) {
  const existingCss = existsSync(cssTarget) ? readFileSync(cssTarget, 'utf8') : ''
  const existingClasses = existsSync(classesTarget) ? readFileSync(classesTarget, 'utf8') : ''
  if (existingCss !== css || existingClasses !== classesOut) {
    console.error(
      `gen-animations-gallery: ${cssTarget} / ${classesTarget} are stale — run \`bun run gen:animations-gallery\` and commit the result.`,
    )
    process.exit(1)
  }
  console.log(`  animations-gallery generated files up to date (${classes.length} animations)`)
} else {
  writeFileSync(cssTarget, css)
  writeFileSync(classesTarget, classesOut)
  console.log(`  generated ${classes.length} animation entries → ${cssTarget}, ${classesTarget}`)
}
